language: python
sudo: false
python:
  - '2.7'
virtualenv:
  system_site_packages: false
addons:
  apt:
    packages:
      - python-pip
cache:
  directories:
    - "$HOME/.cache"
    - "$HOME/.ccache"
before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - python setup.py develop
script:
  - pip install -r dev_requirements.txt
  - flake8 .
  - python -m unittest discover
after_success:
  - pip install codecov
  - codecov
